// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Entities;

namespace WebApi.Migrations
{
    [DbContext(typeof(EmployeContext))]
    [Migration("20220331050531_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.HasSequence<int>("rollno", "dbo");

            modelBuilder.Entity("WebApi.Entities.Attendance", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("integer")
                        .HasDefaultValueSql("NEXT VALUE FOR dbo.Order_seq");

                    b.Property<string>("attendance")
                        .HasColumnType("text");

                    b.Property<string>("firstname")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("WebApi.Entities.Employes", b =>
                {
                    b.Property<int>("rollno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("firstname")
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("lastname")
                        .HasColumnType("text");

                    b.Property<string>("mail")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("phoneno")
                        .HasColumnType("text");

                    b.HasKey("rollno");

                    b.ToTable("Employes");
                });
#pragma warning restore 612, 618
        }
    }
}
